{
 "title": "DP-Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(dpdk_heap_info,cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(dpdk_heap_info{cluster=~\"$cluster\"},pod)"
    }
   },
   {
    "name": "ethdev",
    "query": {
     "query": "label_values(dpdk_ethdev_packets,name)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(dps_firewall_rules_count,interface_id)"
    }
   },
   {
    "name": "hash_table",
    "query": {
     "query": "label_values(dps_hash_table_saturation,table)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Heap Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DP-Service Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Heap_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Free Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Free_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Alloc Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Alloc_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Greatest Free Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Greatest_free_size\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Alloc Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Alloc_count\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "DP-Service Free Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dpdk_heap_info{info=\"Free_count\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  { "title": "DPDK Ethdev statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "DPDK Ethdev PF Link Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "dpdk_ethdev_link_status{cluster=~\"$cluster\", pod=~\"$pod\", name=~\"$ethdev\"}",
     "legendFormat": "{{cluster}} {{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "DPDK Ethdev Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sort(dpdk_ethdev_errors{cluster=~\"$cluster\", pod=~\"$pod\", name=~\"$ethdev\"})",
     "legendFormat": "{{cluster}} {{pod}} {{name}} {{stat}}"
    }
   ]
  },
  {
   "title": "DPDK Ethdev Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sort(dpdk_ethdev_packets{cluster=~\"$cluster\", pod=~\"$pod\", name=~\"$ethdev\"})",
     "legendFormat": "{{cluster}} {{pod}} {{name}} {{stat}}"
    }
   ]
  },
  {
   "title": "DPDK Ethdev Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sort(dpdk_ethdev_bytes{cluster=~\"$cluster\", pod=~\"$pod\", name=~\"$ethdev\"})",
     "legendFormat": "{{cluster}} {{pod}} {{name}} {{stat}}"
    }
   ]
  },
  { "title": "DP-Service statisics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "DP-Service NAT Used Ports per Interface",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sort(dps_nat_used_ports_count{cluster=~\"$cluster\", pod=~\"$pod\", interface_id=~\"$interface\"})",
     "legendFormat": "{{cluster}} {{pod}} {{interface_id}}"
    }
   ]
  },
  {
   "title": "DP-Service Firewall Rules Used per Interface",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "dps_firewall_rules_count{cluster=~\"$cluster\", pod=~\"$pod\", interface_id=~\"$interface\"}",
     "legendFormat": "{{cluster}} {{pod}} {{interface_id}}"
    }
   ]
  },
  {
   "title": "DP-Service VirtualService Used NAT Ports",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "dps_virtsvc_used_ports_count{cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}} {{address}}"
    }
   ]
  },
  {
   "title": "DP-Service Hash Table Saturation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "dps_hash_table_saturation{table=~\"$hash_table\", cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} {{pod}} {{table}}_{{stat}}"
    }
   ]
  }
 ]
}