stages:
  - required_test
  - tested_build
  - untested_build
  - optional_test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

variables:
  GOPRIVATE: "gitlab.devops.telekom.de"
  GOPROXY: "https://proxy.golang.org"
  CODE_QUALITY_DISABLED: "true"
  COMMITID: $CI_COMMIT_SHORT_SHA
  TESTER_TAG: "mtr.devops.telekom.de/osc/onmetal/dpservice-tester:$COMMITID"

.defaults_template:
  image: ${MTR_GITLAB_HOST}/osc/gardener/osc-builder:v7.1.0
  tags:
    - docker
    - pes
    - osc
  before_script:
    - mkdir -p ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - rm -rf ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - mv $CI_PROJECT_DIR ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - mkdir -p $CI_PROJECT_DIR
    - cd ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git

.tester-run-tests:
  image: docker:latest
  tags:
    - docker
    - pes
    - osc
  services:
    - docker:dind
  before_script:
    - |
      running_containers=$(docker ps --format "{{.Names}}" --filter "name=dpservice-go-test-*")
      if [ -n "$running_containers" ]; then
        docker stop $running_containers
      fi
  script:
    - docker load -i dpservice-tester.tar
    # run dpservice-bin tests
    - echo 2048 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
    - docker run --name dpservice-bin-test-$COMMITID --rm --privileged --mount type=bind,source=/dev/hugepages,target=/dev/hugepages $TESTER_TAG
    # run dpservice-go tests
    - docker run --name dpservice-go-test-$COMMITID --rm --entrypoint ./dp_service.py --privileged -p 1337:1337 --mount type=bind,source=/dev/hugepages,target=/dev/hugepages $TESTER_TAG --no-init &
    - sleep 5
    - DPSERVICE_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dpservice-go-test-$COMMITID)
    - apk add --no-cache go
    - cd go/dpservice-go
    - go test -v ./... -ginkgo.randomize-all -args -dpservice_ip=$DPSERVICE_IP
  after_script:
    - |
      if [ "$(docker inspect -f '{{.State.Running}}' dpservice-go-test-$COMMITID 2>/dev/null)" = "true" ]; then
          IMAGE_ID=$(docker inspect --format='{{.Image}}' dpservice-go-test-$COMMITID)
          docker stop dpservice-go-test-$COMMITID
          sleep 10
          docker rmi $IMAGE_ID
      fi

tester-build-required:
  stage: required_test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+/
  image: docker:latest
  tags:
    - docker
    - pes
    - osc
  script:
    - docker build --build-arg=DPSERVICE_FEATURES="-Denable_virtual_services=true" --target tester -t "$TESTER_TAG" .
    - docker save "$TESTER_TAG" -o dpservice-tester.tar
  artifacts:
    paths:
      - dpservice-tester.tar
    expire_in: 1 day

tester-build-optional:
  stage: optional_test
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH =~ /^(feature|bugfix|release-fix)-.+$/
  image: docker:latest
  tags:
    - docker
    - pes
    - osc
  script:
    - docker build --build-arg=DPSERVICE_FEATURES="-Denable_virtual_services=true" --target tester -t "$TESTER_TAG" .
    - docker save "$TESTER_TAG" -o dpservice-tester.tar
  artifacts:
    paths:
      - dpservice-tester.tar
    expire_in: 1 day

build-dev:
  extends: .defaults_template
  stage: untested_build
  script:
    - chmod +x ./hack/build-all.sh ./hack/container-build.sh ./hack/cosign-main.sh
    - ./hack/build-all.sh dev
  only:
    - osc/main

build-branches:
  extends: .defaults_template
  stage: untested_build
  script:
    - chmod +x ./hack/build-all.sh ./hack/container-build.sh ./hack/cosign-main.sh
    - ./hack/build-all.sh ${CI_COMMIT_REF_NAME}
  only:
    - /feature-.*$/
    - /bugfix-.*$/
    - /release-fix-.*$/
  except:
    - tags

build-tag:
  extends: .defaults_template
  stage: tested_build
  needs:
    - tester-test-required
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+/
  script:
    - chmod +x ./hack/build-all.sh ./hack/container-build.sh ./hack/cosign-main.sh
    - ./hack/build-all.sh ${CI_COMMIT_TAG}

tester-test-required:
  extends: .tester-run-tests
  stage: required_test
  needs:
    - tester-build-required
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+/

tester-test-optional:
  extends: .tester-run-tests
  stage: optional_test
  when: manual
  needs:
    - tester-build-optional
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH =~ /^(feature|bugfix|release-fix)-.+$/
