// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

/***********************************************************************/
/*                        DO NOT EDIT THIS FILE                        */
/*                                                                     */
/* This file has been generated by dp_conf_generate.py                 */
/* Please edit dp_conf.json and re-run the script to update this file. */
/***********************************************************************/

#include "dp_argparse.h"

#ifndef ARRAY_SIZE
#	define ARRAY_SIZE(ARRAY) (sizeof(ARRAY) / sizeof((ARRAY)[0]))
#endif

enum {
	OPT_HELP = 'h',
	OPT_VERSION = 'v',
	OPT_OUTPUT_FORMAT = 'o',
	OPT_TABLE = 't',
	OPT_SOCKET = 's',
_OPT_SHOPT_MAX = 255,
	OPT_FILE_PREFIX,
	OPT_DUMP,
};

#define OPTSTRING ":hv" \
	"o:" \
	"t:" \
	"s:" \

static const struct option dp_conf_longopts[] = {
	{ "help", 0, 0, OPT_HELP },
	{ "version", 0, 0, OPT_VERSION },
	{ "file-prefix", 1, 0, OPT_FILE_PREFIX },
	{ "output-format", 1, 0, OPT_OUTPUT_FORMAT },
	{ "table", 1, 0, OPT_TABLE },
	{ "socket", 1, 0, OPT_SOCKET },
	{ "dump", 0, 0, OPT_DUMP },
	{ NULL, 0, 0, 0 }
};

static const char *output_format_choices[] = {
	"human",
	"table",
	"csv",
	"json",
};

static const char *table_choices[] = {
	"list",
	"conntrack",
	"dnat",
	"iface",
	"lb",
	"lb_id",
	"portmap",
	"portoverload",
	"snat",
	"vnf",
	"vnf_rev",
	"vni",
};

static char eal_file_prefix[32];
static enum dp_conf_output_format output_format = DP_CONF_OUTPUT_FORMAT_HUMAN;
static enum dp_conf_table table = DP_CONF_TABLE_LIST;
static int numa_socket = -1;
static bool dump = false;

const char *dp_conf_get_eal_file_prefix(void)
{
	return eal_file_prefix;
}

enum dp_conf_output_format dp_conf_get_output_format(void)
{
	return output_format;
}

enum dp_conf_table dp_conf_get_table(void)
{
	return table;
}

int dp_conf_get_numa_socket(void)
{
	return numa_socket;
}

bool dp_conf_is_dump(void)
{
	return dump;
}



/* These functions need to be implemented by the user of this generated code */
static void dp_argparse_version(void);


static inline void dp_argparse_help(const char *progname, FILE *outfile)
{
	fprintf(outfile, "Usage: %s [options]\n"
		" -h, --help                  display this help and exit\n"
		" -v, --version               display version and exit\n"
		"     --file-prefix=PREFIX    prefix for hugepage filenames\n"
		" -o, --output-format=FORMAT  format of the output: 'human' (default), 'table', 'csv' or 'json'\n"
		" -t, --table=NAME            hash table to choose: 'list' (default), 'conntrack', 'dnat', 'iface', 'lb', 'lb_id', 'portmap', 'portoverload', 'snat', 'vnf', 'vnf_rev' or 'vni'\n"
		" -s, --socket=NUMBER         NUMA socket to use\n"
		"     --dump                  dump table contents\n"
	, progname);
}

static int dp_conf_parse_arg(int opt, const char *arg)
{
	(void)arg;  // if no option uses an argument, this would be unused
	switch (opt) {
	case OPT_FILE_PREFIX:
		return dp_argparse_string(arg, eal_file_prefix, ARRAY_SIZE(eal_file_prefix));
	case OPT_OUTPUT_FORMAT:
		return dp_argparse_enum(arg, (int *)&output_format, output_format_choices, ARRAY_SIZE(output_format_choices));
	case OPT_TABLE:
		return dp_argparse_enum(arg, (int *)&table, table_choices, ARRAY_SIZE(table_choices));
	case OPT_SOCKET:
		return dp_argparse_int(arg, &numa_socket, INT_MIN, INT_MAX);
	case OPT_DUMP:
		return dp_argparse_store_true(&dump);
	default:
		fprintf(stderr, "Unimplemented option %d\n", opt);
		return DP_ERROR;
	}
}

enum dp_conf_runmode dp_conf_parse_args(int argc, char **argv)
{
	const char *progname = argv[0];
	int option_index = -1;
	int opt;

	while ((opt = getopt_long(argc, argv, OPTSTRING, dp_conf_longopts, &option_index)) != -1) {
		switch (opt) {
		case OPT_HELP:
			dp_argparse_help(progname, stdout);
			return DP_CONF_RUNMODE_EXIT;
		case OPT_VERSION:
			dp_argparse_version();
			return DP_CONF_RUNMODE_EXIT;
		case ':':
			fprintf(stderr, "Missing argument for '%s'\n", argv[optind-1]);
			return DP_CONF_RUNMODE_ERROR;
		case '?':
			if (optopt > 0)
				fprintf(stderr, "Unknown option '-%c'\n", optopt);
			else
				fprintf(stderr, "Unknown option '%s'\n", argv[optind-1]);
			return DP_CONF_RUNMODE_ERROR;
		default:
			if (DP_FAILED(dp_conf_parse_arg(opt, optarg))) {
				if (option_index >= 0)
					fprintf(stderr, "Invalid argument for '--%s'\n", dp_conf_longopts[option_index].name);
				else
					fprintf(stderr, "Invalid argument for '-%c'\n", opt);
				return DP_CONF_RUNMODE_ERROR;
			}
		}
		option_index = -1;
	}
	return DP_CONF_RUNMODE_NORMAL;
}

