// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dpdk.proto
#ifndef GRPC_dpdk_2eproto__INCLUDED
#define GRPC_dpdk_2eproto__INCLUDED

#include "dpdk.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace dpdkonmetal {

class PrintHelloWorldService final {
 public:
  static constexpr char const* service_full_name() {
    return "dpdkonmetal.PrintHelloWorldService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status QueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::dpdkonmetal::Status* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dpdkonmetal::Status>> AsyncQueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dpdkonmetal::Status>>(AsyncQueryHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dpdkonmetal::Status>> PrepareAsyncQueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dpdkonmetal::Status>>(PrepareAsyncQueryHelloWorldRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void QueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dpdkonmetal::Status>* AsyncQueryHelloWorldRaw(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dpdkonmetal::Status>* PrepareAsyncQueryHelloWorldRaw(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status QueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::dpdkonmetal::Status* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dpdkonmetal::Status>> AsyncQueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dpdkonmetal::Status>>(AsyncQueryHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dpdkonmetal::Status>> PrepareAsyncQueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dpdkonmetal::Status>>(PrepareAsyncQueryHelloWorldRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void QueryHelloWorld(::grpc::ClientContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dpdkonmetal::Status>* AsyncQueryHelloWorldRaw(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dpdkonmetal::Status>* PrepareAsyncQueryHelloWorldRaw(::grpc::ClientContext* context, const ::dpdkonmetal::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_QueryHelloWorld_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status QueryHelloWorld(::grpc::ServerContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_QueryHelloWorld() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_QueryHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryHelloWorld(::grpc::ServerContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryHelloWorld(::grpc::ServerContext* context, ::dpdkonmetal::Empty* request, ::grpc::ServerAsyncResponseWriter< ::dpdkonmetal::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_QueryHelloWorld<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_QueryHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_QueryHelloWorld() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_QueryHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryHelloWorld(::grpc::ServerContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_QueryHelloWorld() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_QueryHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryHelloWorld(::grpc::ServerContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryHelloWorld(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_QueryHelloWorld() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::dpdkonmetal::Empty, ::dpdkonmetal::Status>(std::bind(&WithStreamedUnaryMethod_QueryHelloWorld<BaseClass>::StreamedQueryHelloWorld, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_QueryHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryHelloWorld(::grpc::ServerContext* context, const ::dpdkonmetal::Empty* request, ::dpdkonmetal::Status* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryHelloWorld(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dpdkonmetal::Empty,::dpdkonmetal::Status>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_QueryHelloWorld<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_QueryHelloWorld<Service > StreamedService;
};

}  // namespace dpdkonmetal


#endif  // GRPC_dpdk_2eproto__INCLUDED
