/***********************************************************************/
/*                        DO NOT EDIT THIS FILE                        */
/*                                                                     */
/* This file has been generated by dp_conf_generate.py                 */
/* Please edit dp_conf.json and re-run the script to update this file. */
/***********************************************************************/

enum dp_conf_nic_type {
	DP_CONF_NIC_TYPE_HW,
	DP_CONF_NIC_TYPE_TAP,
};

enum dp_conf_color {
	DP_CONF_COLOR_NEVER,
	DP_CONF_COLOR_ALWAYS,
	DP_CONF_COLOR_AUTO,
};

enum dp_conf_log_format {
	DP_CONF_LOG_FORMAT_TEXT,
	DP_CONF_LOG_FORMAT_JSON,
};

const char *dp_conf_get_pf0_name(void);
const char *dp_conf_get_pf1_name(void);
const uint8_t *dp_conf_get_underlay_ip(void);
const char *dp_conf_get_vf_pattern(void);
int dp_conf_get_dhcp_mtu(void);
double dp_conf_get_wcmp_frac(void);
enum dp_conf_nic_type dp_conf_get_nic_type(void);
bool dp_conf_is_stats_enabled(void);
bool dp_conf_is_conntrack_enabled(void);
bool dp_conf_is_ipv6_overlay_enabled(void);
bool dp_conf_is_offload_enabled(void);
#ifdef ENABLE_PYTEST
int dp_conf_get_graphtrace_loglevel(void);
#endif
enum dp_conf_color dp_conf_get_color(void);
enum dp_conf_log_format dp_conf_get_log_format(void);
int dp_conf_get_grpc_port(void);
#ifdef ENABLE_PYTEST
int dp_conf_get_flow_timeout(void);
#endif
