/***********************************************************************/
/*                        DO NOT EDIT THIS FILE                        */
/*                                                                     */
/* This file has been generated by dp_conf_generate.py                 */
/* Please edit dp_conf.json and re-run the script to update this file. */
/***********************************************************************/

enum {
	OPT_HELP = 'h',
	OPT_VERSION = 'v',
_OPT_SHOPT_MAX = 255,
	OPT_PF0,
	OPT_PF1,
	OPT_IPV6,
	OPT_VF_PATTERN,
	OPT_OVERLAY_TYPE,
	OPT_DHCP_MTU,
	OPT_DHCP_DNS,
	OPT_WCMP_FRACTION,
	OPT_NIC_TYPE,
	OPT_NO_STATS,
	OPT_NO_CONNTRACK,
	OPT_ENABLE_IPV6_OVERLAY,
	OPT_NO_OFFLOAD,
#ifdef ENABLE_GRAPHTRACE
	OPT_GRAPHTRACE,
#endif
	OPT_COLOR,
	OPT_GRPC_PORT,
};

#define OPTSTRING \
	"h" \
	"v" \

static const struct option longopts[] = {
	{ "help", 0, 0, OPT_HELP },
	{ "version", 0, 0, OPT_VERSION },
	{ "pf0", 1, 0, OPT_PF0 },
	{ "pf1", 1, 0, OPT_PF1 },
	{ "ipv6", 1, 0, OPT_IPV6 },
	{ "vf-pattern", 1, 0, OPT_VF_PATTERN },
	{ "overlay-type", 1, 0, OPT_OVERLAY_TYPE },
	{ "dhcp-mtu", 1, 0, OPT_DHCP_MTU },
	{ "dhcp-dns", 1, 0, OPT_DHCP_DNS },
	{ "wcmp-fraction", 1, 0, OPT_WCMP_FRACTION },
	{ "nic-type", 1, 0, OPT_NIC_TYPE },
	{ "no-stats", 0, 0, OPT_NO_STATS },
	{ "no-conntrack", 0, 0, OPT_NO_CONNTRACK },
	{ "enable-ipv6-overlay", 0, 0, OPT_ENABLE_IPV6_OVERLAY },
	{ "no-offload", 0, 0, OPT_NO_OFFLOAD },
#ifdef ENABLE_GRAPHTRACE
	{ "graphtrace", 1, 0, OPT_GRAPHTRACE },
#endif
	{ "color", 1, 0, OPT_COLOR },
	{ "grpc-port", 1, 0, OPT_GRPC_PORT },
	{ NULL, }
};

static const char *overlay_type_choices[] = {
	"ipip",
	"geneve",
};

static const char *nic_type_choices[] = {
	"hw",
	"tap",
};

static const char *color_choices[] = {
	"never",
	"always",
	"auto",
};

static void print_help_args(FILE *outfile)
{
	fprintf(outfile, "%s",
		" -h, --help                    display this help and exit\n"
		" -v, --version                 display version and exit\n"
		"     --pf0=IFNAME              first physical interface (e.g. eth0)\n"
		"     --pf1=IFNAME              second physical interface (e.g. eth1)\n"
		"     --ipv6=ADDR6              IPv6 underlay address\n"
		"     --vf-pattern=PATTERN      virtual interface name pattern (e.g. 'eth1vf')\n"
		"     --overlay-type=TYPE       overlay tunnel type to use: 'ipip' (default) or 'geneve'\n"
		"     --dhcp-mtu=SIZE           set the mtu field in DHCP responses (68 - 1500)\n"
		"     --dhcp-dns=IPv4           set the domain name server field in DHCP responses (can be used multiple times)\n"
		"     --wcmp-fraction=FRACTION  weighted-cost-multipath coefficient for pf0 (0.0 - 1.0)\n"
		"     --nic-type=NICTYPE        NIC type to use: 'hw' (default) or 'tap'\n"
		"     --no-stats                do not print periodic statistics to stdout\n"
		"     --no-conntrack            disable connection tracking\n"
		"     --enable-ipv6-overlay     enable IPv6 overlay addresses\n"
		"     --no-offload              disable traffic offloading\n"
#ifdef ENABLE_GRAPHTRACE
		"     --graphtrace=LEVEL        verbosity level of packet traversing the graph framework\n"
#endif
		"     --color=MODE              output colorization mode: 'never' (default), 'always' or 'auto'\n"
		"     --grpc-port=PORT          listen for gRPC clients on this port\n"
	);
}

static char pf0_name[IF_NAMESIZE];
static char pf1_name[IF_NAMESIZE];
static char vf_pattern[IF_NAMESIZE];
static enum dp_conf_overlay_type overlay_type = DP_CONF_OVERLAY_TYPE_IPIP;
static int dhcp_mtu = 1500;
static double wcmp_frac = 1.0;
static enum dp_conf_nic_type nic_type = DP_CONF_NIC_TYPE_HW;
static bool stats_enabled = true;
static bool conntrack_enabled = true;
static bool ipv6_overlay_enabled = false;
static bool offload_enabled = true;
#ifdef ENABLE_GRAPHTRACE
static int graphtrace_level = 0;
#endif
static enum dp_conf_color color = DP_CONF_COLOR_NEVER;
static int grpc_port = 1337;

const char *dp_conf_get_pf0_name()
{
	return pf0_name;
}

const char *dp_conf_get_pf1_name()
{
	return pf1_name;
}

const char *dp_conf_get_vf_pattern()
{
	return vf_pattern;
}

const enum dp_conf_overlay_type dp_conf_get_overlay_type()
{
	return overlay_type;
}

const int dp_conf_get_dhcp_mtu()
{
	return dhcp_mtu;
}

const double dp_conf_get_wcmp_frac()
{
	return wcmp_frac;
}

const enum dp_conf_nic_type dp_conf_get_nic_type()
{
	return nic_type;
}

const bool dp_conf_is_stats_enabled()
{
	return stats_enabled;
}

const bool dp_conf_is_conntrack_enabled()
{
	return conntrack_enabled;
}

const bool dp_conf_is_ipv6_overlay_enabled()
{
	return ipv6_overlay_enabled;
}

const bool dp_conf_is_offload_enabled()
{
	return offload_enabled;
}

#ifdef ENABLE_GRAPHTRACE
const int dp_conf_get_graphtrace_level()
{
	return graphtrace_level;
}

#endif
const enum dp_conf_color dp_conf_get_color()
{
	return color;
}

const int dp_conf_get_grpc_port()
{
	return grpc_port;
}

