/***********************************************************************/
/*                        DO NOT EDIT THIS FILE                        */
/*                                                                     */
/* This file has been generated by dp_conf_generate.py                 */
/* Please edit dp_conf.json and re-run the script to update this file. */
/***********************************************************************/

bool dp_conf_is_showing_drops(void);
bool dp_conf_is_showing_nodes(void);
bool dp_conf_is_offload_enabled(void);
bool dp_conf_is_stop_mode(void);
